services:

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rmq-cont
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - 'rmq-data:/var/lib/rabbitmq'
    networks:
      - bank-ms-net
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 1234

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.1
    ports:
      - "4000:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: 1234
    command: "start-dev"

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - bank-ms-net

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - bank-ms-net

  config-server-ms:
    build: ../../services/configserver
    container_name: configserver-cont
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5

    extends:
      file: common-qa.yml
      service: ms-parent-service

  eureka-server-ms:
    build: ../../services/eurekaserver
    container_name: eurekaserver-cont
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5
    extends:
      file: common-qa.yml
      service: ms-parent-service
    depends_on:
      config-server-ms:
        condition: service_healthy

  accounts-ms-r1:
    build: ../../services/accounts
    container_name: accounts-cont
    ports:
      - "8080:8080"
    extends:
      file: common-qa.yml
      service: business-ms-parent

  #accounts-ms-r2:
  #  build: ../../services/accounts
  #  container_name: accounts-cont
  #  ports:
  #    - "8081:8080"
  #  extends:
  #    file: common-qa.yml
  #    service: business-ms-parent


  cards-ms:
    build: ../../services/cards
    container_name: cards-cont
    ports:
      - "9000:9000"
    extends:
      file: common-qa.yml
      service: business-ms-parent

  loans-ms:
    build: ../../services/loans
    container_name: loans-cont
    ports:
      - "8090:8090"
    extends:
      file: common-qa.yml
      service: business-ms-parent

  gateway-server-ms:
    build: ../../services/gatewayserver
    container_name: gatewayserver-cont
    ports:
      - "8085:8085"
    extends:
      file: common-qa.yml
      service: business-ms-parent


networks:
  bank-ms-net:
    driver: bridge

volumes:
  rmq-data:
  keycloak-data:
