spring:
  application:
    name: api-gateway

  config:
    import: "optional:configserver:http://localhost:8888/"


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:4000/realms/master/protocol/openid-connect/certs"

resilience4j.circuitbreaker:
  instances:
    accounts-circuit-breaker:
      slidingWindowSize: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permitted-number-of-calls-in-half-open-state: 2
    cards-circuit-breaker:
      slidingWindowSize: 5
      failureRateThreshold: 60
      waitDurationInOpenState: 15s
      permitted-number-of-calls-in-half-open-state: 2

management:
  tracing:
    enabled: true
    sampling:
      probability: 1