services:
  postgres-parent-service:
    image: postgres:18
    networks:
      - bank-ms-net
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5


  pgAdmin:
    image: 'dpage/pgadmin4'
    container_name: pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=yuji@yopmail.com
      - PGADMIN_DEFAULT_PASSWORD=53cret
    ports:
      - '5050:80'
    depends_on:
      postgres-accounts:
        condition: service_healthy
      postgres-cards:
        condition: service_healthy
      postgres-loans:
        condition: service_healthy

    restart: always
    networks:
      - bank-ms-net
